apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspire-manager
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspire-manager
  template:
    metadata:
      labels:
        app: inspire-manager
    spec:
      containers:
        - name: inspire-manager
          image: uhub.service.ucloud.cn/entropypool/inspire-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/GoodManager
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: inspire-manager-config
            items:
              - key: service-conf
                path: GoodManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: inspire-manager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50670
      targetPort: 50670
    - name: grpc
      port: 50671
      targetPort: 50671
    - name: healthz
      port: 50672
      targetPort: 50672
    - name: prometheus
      port: 50673
      targetPort: 50673
  selector:
    app: inspire-manager
